name: Compile package
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX file
        uses: xu-cheng/texlive-action@v3
        with:
          run: |
            pdflatex collabcomment.dtx
            makeindex -s gind.ist -o collabcomment.ind collabcomment.idx
            makeindex -s gglo.ist -o collabcomment.gls collabcomment.glo
            pdflatex collabcomment.dtx
      - name: Move CTAN files into folder
        run: |
          mkdir -p ctan/collabcomment
          mv orgstyle.dtx ctan/collabcomment/collabcomment.dtx
          mv orgstyle.ins ctan/collabcomment/collabcomment.ins
          mv README.md ctan/collabcomment/README.md
          mv orgstyle.pdf ctan/collabcomment/collabcomment-doc.pdf
      - name: Zip CTAN files
        uses: actions/upload-artifact@v4
        with:
          name: CTAN-files
          path: ctan/
      - name: Zip sty file
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: collabcomment.sty